version: "3.7"
services:
    api:
        image: ghcr.io/jj-8/ctfnote/api:latest
        extends:
            file: docker-compose.yml
            service: api
    db:
        image: ghcr.io/jj-8/ctfnote/db:latest
        extends:
            file: docker-compose.yml
            service: db
    front:
        image: ghcr.io/jj-8/ctfnote/front:latest
        extends:
            file: docker-compose.yml
            service: front
    hedgedoc:
        extends:
            file: docker-compose.yml
            service: hedgedoc
volumes:
    ctfnote-db:
        name: ctfnote
    ctfnote-uploads:
        name: ctfnote-uploads
    pad-uploads:
        name: pad-uploads
networks:
    ctfnote:
