mutation updateCredentialsForCtfId($ctfId: Int!, $credentials: String) {
	updateCtfSecret(input: { id: $ctfId, patch: { credentials: $credentials}}) {
			ctfSecret {
				nodeId
				credentials
			}
		}
	}