mutation ChangePassword($oldPassword: String!, $newPassword: String!) {
  changePassword(input: { oldpassword: $oldPassword, newpassword: $newPassword }) {
    changePasswordResponse {
      ok
    }
  }
}
