#import "./TaskInfo.gql"

subscription SubscribeTask($topic: String!) {
  listen(topic: $topic) {
    relatedNodeId
    relatedNode {
      nodeId
      ... on Task {
        ...TaskInfo
      }
    }
  }
}
