#import "./InvitationInfo.gql"
mutation inviteUser($ctfId: Int!, $profileId: Int!) {
  createInvitation(input:{invitation:{ctfId: $ctfId, profileId: $profileId}}){
    invitation{
			...InvitationInfo			
    }
  }
}